version: '3.9'
services:
  meterly-container:
    image: ruliseun/meterly:latest
    ports:
      - 3012:3012
      - 1025:1025
      - 1080:1080
    environment:
      - DOCKER_OPTS=--ipv6=false
    deploy:
      resources:
        limits:
          memory: 1000m
          cpus: '0.3'
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
