export default [
  {
    name: "Afghanistan",
    dialCode: "+93",
    countryCode: "AF",
    currencyCode: "AFN",
  },
  {
    name: "Aland Islands",
    dialCode: "+358",
    countryCode: "AX",
    currencyCode: "EUR",
  },
  {
    name: "Albania",
    dialCode: "+355",
    countryCode: "AL",
    currencyCode: "ALL",
  },
  {
    name: "Algeria",
    dialCode: "+213",
    countryCode: "DZ",
    currencyCode: "DZD",
  },
  {
    name: "AmericanSamoa",
    dialCode: "+1684",
    countryCode: "AS",
    currencyCode: "USD",
  },
  {
    name: "Andorra",
    dialCode: "+376",
    countryCode: "AD",
    currencyCode: "EUR",
  },
  {
    name: "Angola",
    dialCode: "+244",
    countryCode: "AO",
    currencyCode: "AOA",
  },
  {
    name: "Anguilla",
    dialCode: "+1264",
    countryCode: "AI",
    currencyCode: "XCD",
  },
  {
    name: "Antarctica",
    dialCode: "+672",
    countryCode: "AQ",
    currencyCode: "",
  },
  {
    name: "Antigua and Barbuda",
    dialCode: "+1268",
    countryCode: "AG",
    currencyCode: "XCD",
  },
  {
    name: "Argentina",
    dialCode: "+54",
    countryCode: "AR",
    currencyCode: "ARS",
  },
  {
    name: "Armenia",
    dialCode: "+374",
    countryCode: "AM",
    currencyCode: "AMD",
  },
  {
    name: "Aruba",
    dialCode: "+297",
    countryCode: "AW",
    currencyCode: "AWG",
  },
  {
    name: "Australia",
    dialCode: "+61",
    countryCode: "AU",
    currencyCode: "AUD",
  },
  {
    name: "Austria",
    dialCode: "+43",
    countryCode: "AT",
    currencyCode: "EUR",
  },
  {
    name: "Azerbaijan",
    dialCode: "+994",
    countryCode: "AZ",
    currencyCode: "AZN",
  },
  {
    name: "Bahamas",
    dialCode: "+1242",
    countryCode: "BS",
    currencyCode: "BSD",
  },
  {
    name: "Bahrain",
    dialCode: "+973",
    countryCode: "BH",
    currencyCode: "BHD",
  },
  {
    name: "Bangladesh",
    dialCode: "+880",
    countryCode: "BD",
    currencyCode: "BDT",
  },
  {
    name: "Barbados",
    dialCode: "+1246",
    countryCode: "BB",
    currencyCode: "BBD",
  },
  {
    name: "Belarus",
    dialCode: "+375",
    countryCode: "BY",
    currencyCode: "BYR",
  },
  {
    name: "Belgium",
    dialCode: "+32",
    countryCode: "BE",
    currencyCode: "EUR",
  },
  {
    name: "Belize",
    dialCode: "+501",
    countryCode: "BZ",
    currencyCode: "BZD",
  },
  {
    name: "Benin",
    dialCode: "+229",
    countryCode: "BJ",
    currencyCode: "XOF",
  },
  {
    name: "Bermuda",
    dialCode: "+1441",
    countryCode: "BM",
    currencyCode: "BMD",
  },
  {
    name: "Bhutan",
    dialCode: "+975",
    countryCode: "BT",
    currencyCode: "BTN",
  },
  {
    name: "Bolivia, Plurinational State of",
    dialCode: "+591",
    countryCode: "BO",
    currencyCode: "BOB",
  },
  {
    name: "Bosnia and Herzegovina",
    dialCode: "+387",
    countryCode: "BA",
    currencyCode: "BAM",
  },
  {
    name: "Botswana",
    dialCode: "+267",
    countryCode: "BW",
    currencyCode: "BWP",
  },
  {
    name: "Brazil",
    dialCode: "+55",
    countryCode: "BR",
    currencyCode: "BRL",
  },
  {
    name: "British Indian Ocean Territory",
    dialCode: "+246",
    countryCode: "IO",
    currencyCode: "USD",
  },
  {
    name: "Brunei Darussalam",
    dialCode: "+673",
    countryCode: "BN",
    currencyCode: "BND",
  },
  {
    name: "Bulgaria",
    dialCode: "+359",
    countryCode: "BG",
    currencyCode: "BGN",
  },
  {
    name: "Burkina Faso",
    dialCode: "+226",
    countryCode: "BF",
    currencyCode: "XOF",
  },
  {
    name: "Burundi",
    dialCode: "+257",
    countryCode: "BI",
    currencyCode: "BIF",
  },
  {
    name: "Cambodia",
    dialCode: "+855",
    countryCode: "KH",
    currencyCode: "KHR",
  },
  {
    name: "Cameroon",
    dialCode: "+237",
    countryCode: "CM",
    currencyCode: "XAF",
  },
  {
    name: "Canada",
    dialCode: "+1",
    countryCode: "CA",
    currencyCode: "CAD",
  },
  {
    name: "Cape Verde",
    dialCode: "+238",
    countryCode: "CV",
    currencyCode: "CVE",
  },
  {
    name: "Cayman Islands",
    dialCode: "+ 345",
    countryCode: "KY",
    currencyCode: "KYD",
  },
  {
    name: "Central African Republic",
    dialCode: "+236",
    countryCode: "CF",
    currencyCode: "XAF",
  },
  {
    name: "Chad",
    dialCode: "+235",
    countryCode: "TD",
    currencyCode: "XAF",
  },
  {
    name: "Chile",
    dialCode: "+56",
    countryCode: "CL",
    currencyCode: "CLP",
  },
  {
    name: "China",
    dialCode: "+86",
    countryCode: "CN",
    currencyCode: "CNY",
  },
  {
    name: "Christmas Island",
    dialCode: "+61",
    countryCode: "CX",
    currencyCode: "AUD",
  },
  {
    name: "Cocos (Keeling) Islands",
    dialCode: "+61",
    countryCode: "CC",
    currencyCode: "AUD",
  },
  {
    name: "Colombia",
    dialCode: "+57",
    countryCode: "CO",
    currencyCode: "COP",
  },
  {
    name: "Comoros",
    dialCode: "+269",
    countryCode: "KM",
    currencyCode: "KMF",
  },
  {
    name: "Congo",
    dialCode: "+242",
    countryCode: "CG",
    currencyCode: "XAF",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dialCode: "+243",
    countryCode: "CD",
    currencyCode: "CDF",
  },
  {
    name: "Cook Islands",
    dialCode: "+682",
    countryCode: "CK",
    currencyCode: "NZD",
  },
  {
    name: "Costa Rica",
    dialCode: "+506",
    countryCode: "CR",
    currencyCode: "CRC",
  },
  {
    name: "Cote d'Ivoire",
    dialCode: "+225",
    countryCode: "CI",
    currencyCode: "XOF",
  },
  {
    name: "Croatia",
    dialCode: "+385",
    countryCode: "HR",
    currencyCode: "HRK",
  },
  {
    name: "Cuba",
    dialCode: "+53",
    countryCode: "CU",
    currencyCode: "CUP",
  },
  {
    name: "Cyprus",
    dialCode: "+357",
    countryCode: "CY",
    currencyCode: "EUR",
  },
  {
    name: "Czech Republic",
    dialCode: "+420",
    countryCode: "CZ",
    currencyCode: "CZK",
  },
  {
    name: "Denmark",
    dialCode: "+45",
    countryCode: "DK",
    currencyCode: "DKK",
  },
  {
    name: "Djibouti",
    dialCode: "+253",
    countryCode: "DJ",
    currencyCode: "DJF",
  },
  {
    name: "Dominica",
    dialCode: "+1767",
    countryCode: "DM",
    currencyCode: "XCD",
  },
  {
    name: "Dominican Republic",
    dialCode: "+1849",
    countryCode: "DO",
    currencyCode: "DOP",
  },
  {
    name: "Ecuador",
    dialCode: "+593",
    countryCode: "EC",
    currencyCode: "USD",
  },
  {
    name: "Egypt",
    dialCode: "+20",
    countryCode: "EG",
    currencyCode: "EGP",
  },
  {
    name: "El Salvador",
    dialCode: "+503",
    countryCode: "SV",
    currencyCode: "USD",
  },
  {
    name: "Equatorial Guinea",
    dialCode: "+240",
    countryCode: "GQ",
    currencyCode: "XAF",
  },
  {
    name: "Eritrea",
    dialCode: "+291",
    countryCode: "ER",
    currencyCode: "ERN",
  },
  {
    name: "Estonia",
    dialCode: "+372",
    countryCode: "EE",
    currencyCode: "EUR",
  },
  {
    name: "Ethiopia",
    dialCode: "+251",
    countryCode: "ET",
    currencyCode: "ETB",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dialCode: "+500",
    countryCode: "FK",
    currencyCode: "FKP",
  },
  {
    name: "Faroe Islands",
    dialCode: "+298",
    countryCode: "FO",
    currencyCode: "DKK",
  },
  {
    name: "Fiji",
    dialCode: "+679",
    countryCode: "FJ",
    currencyCode: "FJD",
  },
  {
    name: "Finland",
    dialCode: "+358",
    countryCode: "FI",
    currencyCode: "EUR",
  },
  {
    name: "France",
    dialCode: "+33",
    countryCode: "FR",
    currencyCode: "EUR",
  },
  {
    name: "French Guiana",
    dialCode: "+594",
    countryCode: "GF",
    currencyCode: "EUR",
  },
  {
    name: "French Polynesia",
    dialCode: "+689",
    countryCode: "PF",
    currencyCode: "XPF",
  },
  {
    name: "Gabon",
    dialCode: "+241",
    countryCode: "GA",
    currencyCode: "XAF",
  },
  {
    name: "Gambia",
    dialCode: "+220",
    countryCode: "GM",
    currencyCode: "GMD",
  },
  {
    name: "Georgia",
    dialCode: "+995",
    countryCode: "GE",
    currencyCode: "GEL",
  },
  {
    name: "Germany",
    dialCode: "+49",
    countryCode: "DE",
    currencyCode: "EUR",
  },
  {
    name: "Ghana",
    dialCode: "+233",
    countryCode: "GH",
    currencyCode: "GHS",
  },
  {
    name: "Gibraltar",
    dialCode: "+350",
    countryCode: "GI",
    currencyCode: "GIP",
  },
  {
    name: "Greece",
    dialCode: "+30",
    countryCode: "GR",
    currencyCode: "EUR",
  },
  {
    name: "Greenland",
    dialCode: "+299",
    countryCode: "GL",
    currencyCode: "DKK",
  },
  {
    name: "Grenada",
    dialCode: "+1473",
    countryCode: "GD",
    currencyCode: "XCD",
  },
  {
    name: "Guadeloupe",
    dialCode: "+590",
    countryCode: "GP",
    currencyCode: "EUR",
  },
  {
    name: "Guam",
    dialCode: "+1671",
    countryCode: "GU",
    currencyCode: "USD",
  },
  {
    name: "Guatemala",
    dialCode: "+502",
    countryCode: "GT",
    currencyCode: "GTQ",
  },
  {
    name: "Guernsey",
    dialCode: "+44",
    countryCode: "GG",
    currencyCode: "GBP",
  },
  {
    name: "Guinea",
    dialCode: "+224",
    countryCode: "GN",
    currencyCode: "GNF",
  },
  {
    name: "Guinea-Bissau",
    dialCode: "+245",
    countryCode: "GW",
    currencyCode: "XOF",
  },
  {
    name: "Guyana",
    dialCode: "+595",
    countryCode: "GY",
    currencyCode: "GYD",
  },
  {
    name: "Haiti",
    dialCode: "+509",
    countryCode: "HT",
    currencyCode: "HTG",
  },
  {
    name: "Holy See (Vatican City State)",
    dialCode: "+379",
    countryCode: "VA",
    currencyCode: "EUR",
  },
  {
    name: "Honduras",
    dialCode: "+504",
    countryCode: "HN",
    currencyCode: "HNL",
  },
  {
    name: "Hong Kong",
    dialCode: "+852",
    countryCode: "HK",
    currencyCode: "HKD",
  },
  {
    name: "Hungary",
    dialCode: "+36",
    countryCode: "HU",
    currencyCode: "HUF",
  },
  {
    name: "Iceland",
    dialCode: "+354",
    countryCode: "IS",
    currencyCode: "ISK",
  },
  {
    name: "India",
    dialCode: "+91",
    countryCode: "IN",
    currencyCode: "INR",
  },
  {
    name: "Indonesia",
    dialCode: "+62",
    countryCode: "ID",
    currencyCode: "IDR",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dialCode: "+98",
    countryCode: "IR",
    currencyCode: "IRR",
  },
  {
    name: "Iraq",
    dialCode: "+964",
    countryCode: "IQ",
    currencyCode: "IQD",
  },
  {
    name: "Ireland",
    dialCode: "+353",
    countryCode: "IE",
    currencyCode: "EUR",
  },
  {
    name: "Isle of Man",
    dialCode: "+44",
    countryCode: "IM",
    currencyCode: "GBP",
  },
  {
    name: "Israel",
    dialCode: "+972",
    countryCode: "IL",
    currencyCode: "ILS",
  },
  {
    name: "Italy",
    dialCode: "+39",
    countryCode: "IT",
    currencyCode: "EUR",
  },
  {
    name: "Jamaica",
    dialCode: "+1876",
    countryCode: "JM",
    currencyCode: "JMD",
  },
  {
    name: "Japan",
    dialCode: "+81",
    countryCode: "JP",
    currencyCode: "JPY",
  },
  {
    name: "Jersey",
    dialCode: "+44",
    countryCode: "JE",
    currencyCode: "GBP",
  },
  {
    name: "Jordan",
    dialCode: "+962",
    countryCode: "JO",
    currencyCode: "JOD",
  },
  {
    name: "Kazakhstan",
    dialCode: "+77",
    countryCode: "KZ",
    currencyCode: "KZT",
  },
  {
    name: "Kenya",
    dialCode: "+254",
    countryCode: "KE",
    currencyCode: "KES",
  },
  {
    name: "Kiribati",
    dialCode: "+686",
    countryCode: "KI",
    currencyCode: "AUD",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dialCode: "+850",
    countryCode: "KP",
    currencyCode: "KPW",
  },
  {
    name: "Korea, Republic of South Korea",
    dialCode: "+82",
    countryCode: "KR",
    currencyCode: "KRW",
  },
  {
    name: "Kuwait",
    dialCode: "+965",
    countryCode: "KW",
    currencyCode: "KWD",
  },
  {
    name: "Kyrgyzstan",
    dialCode: "+996",
    countryCode: "KG",
    currencyCode: "KGS",
  },
  {
    name: "Laos",
    dialCode: "+856",
    countryCode: "LA",
    currencyCode: "LAK",
  },
  {
    name: "Latvia",
    dialCode: "+371",
    countryCode: "LV",
    currencyCode: "EUR",
  },
  {
    name: "Lebanon",
    dialCode: "+961",
    countryCode: "LB",
    currencyCode: "LBP",
  },
  {
    name: "Lesotho",
    dialCode: "+266",
    countryCode: "LS",
    currencyCode: "LSL",
  },
  {
    name: "Liberia",
    dialCode: "+231",
    countryCode: "LR",
    currencyCode: "LRD",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dialCode: "+218",
    countryCode: "LY",
    currencyCode: "LYD",
  },
  {
    name: "Liechtenstein",
    dialCode: "+423",
    countryCode: "LI",
    currencyCode: "CHF",
  },
  {
    name: "Lithuania",
    dialCode: "+370",
    countryCode: "LT",
    currencyCode: "EUR",
  },
  {
    name: "Luxembourg",
    dialCode: "+352",
    countryCode: "LU",
    currencyCode: "EUR",
  },
  {
    name: "Macao",
    dialCode: "+853",
    countryCode: "MO",
    currencyCode: "MOP",
  },
  {
    name: "Macedonia",
    dialCode: "+389",
    countryCode: "MK",
    currencyCode: "MKD",
  },
  {
    name: "Madagascar",
    dialCode: "+261",
    countryCode: "MG",
    currencyCode: "MGA",
  },
  {
    name: "Malawi",
    dialCode: "+265",
    countryCode: "MW",
    currencyCode: "MWK",
  },
  {
    name: "Malaysia",
    dialCode: "+60",
    countryCode: "MY",
    currencyCode: "MYR",
  },
  {
    name: "Maldives",
    dialCode: "+960",
    countryCode: "MV",
    currencyCode: "MVR",
  },
  {
    name: "Mali",
    dialCode: "+223",
    countryCode: "ML",
    currencyCode: "XOF",
  },
  {
    name: "Malta",
    dialCode: "+356",
    countryCode: "MT",
    currencyCode: "EUR",
  },
  {
    name: "Marshall Islands",
    dialCode: "+692",
    countryCode: "MH",
    currencyCode: "USD",
  },
  {
    name: "Martinique",
    dialCode: "+596",
    countryCode: "MQ",
    currencyCode: "EUR",
  },
  {
    name: "Mauritania",
    dialCode: "+222",
    countryCode: "MR",
    currencyCode: "MRO",
  },
  {
    name: "Mauritius",
    dialCode: "+230",
    countryCode: "MU",
    currencyCode: "MUR",
  },
  {
    name: "Mayotte",
    dialCode: "+262",
    countryCode: "YT",
    currencyCode: "EUR",
  },
  {
    name: "Mexico",
    dialCode: "+52",
    countryCode: "MX",
    currencyCode: "MXN",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dialCode: "+691",
    countryCode: "FM",
    currencyCode: "USD",
  },
  {
    name: "Moldova",
    dialCode: "+373",
    countryCode: "MD",
    currencyCode: "MDL",
  },
  {
    name: "Monaco",
    dialCode: "+377",
    countryCode: "MC",
    currencyCode: "EUR",
  },
  {
    name: "Mongolia",
    dialCode: "+976",
    countryCode: "MN",
    currencyCode: "MNT",
  },
  {
    name: "Montenegro",
    dialCode: "+382",
    countryCode: "ME",
    currencyCode: "EUR",
  },
  {
    name: "Montserrat",
    dialCode: "+1664",
    countryCode: "MS",
    currencyCode: "XCD",
  },
  {
    name: "Morocco",
    dialCode: "+212",
    countryCode: "MA",
    currencyCode: "MAD",
  },
  {
    name: "Mozambique",
    dialCode: "+258",
    countryCode: "MZ",
    currencyCode: "MZN",
  },
  {
    name: "Myanmar",
    dialCode: "+95",
    countryCode: "MM",
    currencyCode: "MMK",
  },
  {
    name: "Namibia",
    dialCode: "+264",
    countryCode: "NA",
    currencyCode: "NAD",
  },
  {
    name: "Nauru",
    dialCode: "+674",
    countryCode: "NR",
    currencyCode: "AUD",
  },
  {
    name: "Nepal",
    dialCode: "+977",
    countryCode: "NP",
    currencyCode: "NPR",
  },
  {
    name: "Netherlands",
    dialCode: "+31",
    countryCode: "NL",
    currencyCode: "EUR",
  },
  {
    name: "Netherlands Antilles",
    dialCode: "+599",
    countryCode: "AN",
    currencyCode: "",
  },
  {
    name: "New Caledonia",
    dialCode: "+687",
    countryCode: "NC",
    currencyCode: "XPF",
  },
  {
    name: "New Zealand",
    dialCode: "+64",
    countryCode: "NZ",
    currencyCode: "NZD",
  },
  {
    name: "Nicaragua",
    dialCode: "+505",
    countryCode: "NI",
    currencyCode: "NIO",
  },
  {
    name: "Niger",
    dialCode: "+227",
    countryCode: "NE",
    currencyCode: "XOF",
  },
  {
    name: "Nigeria",
    dialCode: "+234",
    countryCode: "NG",
    currencyCode: "NGN",
  },
  {
    name: "Niue",
    dialCode: "+683",
    countryCode: "NU",
    currencyCode: "NZD",
  },
  {
    name: "Norfolk Island",
    dialCode: "+672",
    countryCode: "NF",
    currencyCode: "AUD",
  },
  {
    name: "Northern Mariana Islands",
    dialCode: "+1670",
    countryCode: "MP",
    currencyCode: "USD",
  },
  {
    name: "Norway",
    dialCode: "+47",
    countryCode: "NO",
    currencyCode: "NOK",
  },
  {
    name: "Oman",
    dialCode: "+968",
    countryCode: "OM",
    currencyCode: "OMR",
  },
  {
    name: "Pakistan",
    dialCode: "+92",
    countryCode: "PK",
    currencyCode: "PKR",
  },
  {
    name: "Palau",
    dialCode: "+680",
    countryCode: "PW",
    currencyCode: "USD",
  },
  {
    name: "Palestinian Territory, Occupied",
    dialCode: "+970",
    countryCode: "PS",
    currencyCode: "ILS",
  },
  {
    name: "Panama",
    dialCode: "+507",
    countryCode: "PA",
    currencyCode: "PAB",
  },
  {
    name: "Papua New Guinea",
    dialCode: "+675",
    countryCode: "PG",
    currencyCode: "PGK",
  },
  {
    name: "Paraguay",
    dialCode: "+595",
    countryCode: "PY",
    currencyCode: "PYG",
  },
  {
    name: "Peru",
    dialCode: "+51",
    countryCode: "PE",
    currencyCode: "PEN",
  },
  {
    name: "Philippines",
    dialCode: "+63",
    countryCode: "PH",
    currencyCode: "PHP",
  },
  {
    name: "Pitcairn",
    dialCode: "+872",
    countryCode: "PN",
    currencyCode: "NZD",
  },
  {
    name: "Poland",
    dialCode: "+48",
    countryCode: "PL",
    currencyCode: "PLN",
  },
  {
    name: "Portugal",
    dialCode: "+351",
    countryCode: "PT",
    currencyCode: "EUR",
  },
  {
    name: "Puerto Rico",
    dialCode: "+1939",
    countryCode: "PR",
    currencyCode: "USD",
  },
  {
    name: "Qatar",
    dialCode: "+974",
    countryCode: "QA",
    currencyCode: "QAR",
  },
  {
    name: "Romania",
    dialCode: "+40",
    countryCode: "RO",
    currencyCode: "RON",
  },
  {
    name: "Russia",
    dialCode: "+7",
    countryCode: "RU",
    currencyCode: "RUB",
  },
  {
    name: "Rwanda",
    dialCode: "+250",
    countryCode: "RW",
    currencyCode: "RWF",
  },
  {
    name: "Reunion",
    dialCode: "+262",
    countryCode: "RE",
    currencyCode: "EUR",
  },
  {
    name: "Saint Barthelemy",
    dialCode: "+590",
    countryCode: "BL",
    currencyCode: "EUR",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dialCode: "+290",
    countryCode: "SH",
    currencyCode: "SHP",
  },
  {
    name: "Saint Kitts and Nevis",
    dialCode: "+1869",
    countryCode: "KN",
    currencyCode: "XCD",
  },
  {
    name: "Saint Lucia",
    dialCode: "+1758",
    countryCode: "LC",
    currencyCode: "XCD",
  },
  {
    name: "Saint Martin",
    dialCode: "+590",
    countryCode: "MF",
    currencyCode: "EUR",
  },
  {
    name: "Saint Pierre and Miquelon",
    dialCode: "+508",
    countryCode: "PM",
    currencyCode: "EUR",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dialCode: "+1784",
    countryCode: "VC",
    currencyCode: "XCD",
  },
  {
    name: "Samoa",
    dialCode: "+685",
    countryCode: "WS",
    currencyCode: "WST",
  },
  {
    name: "San Marino",
    dialCode: "+378",
    countryCode: "SM",
    currencyCode: "EUR",
  },
  {
    name: "Sao Tome and Principe",
    dialCode: "+239",
    countryCode: "ST",
    currencyCode: "STD",
  },
  {
    name: "Saudi Arabia",
    dialCode: "+966",
    countryCode: "SA",
    currencyCode: "SAR",
  },
  {
    name: "Senegal",
    dialCode: "+221",
    countryCode: "SN",
    currencyCode: "XOF",
  },
  {
    name: "Serbia",
    dialCode: "+381",
    countryCode: "RS",
    currencyCode: "RSD",
  },
  {
    name: "Seychelles",
    dialCode: "+248",
    countryCode: "SC",
    currencyCode: "SCR",
  },
  {
    name: "Sierra Leone",
    dialCode: "+232",
    countryCode: "SL",
    currencyCode: "SLL",
  },
  {
    name: "Singapore",
    dialCode: "+65",
    countryCode: "SG",
    currencyCode: "SGD",
  },
  {
    name: "Slovakia",
    dialCode: "+421",
    countryCode: "SK",
    currencyCode: "EUR",
  },
  {
    name: "Slovenia",
    dialCode: "+386",
    countryCode: "SI",
    currencyCode: "EUR",
  },
  {
    name: "Solomon Islands",
    dialCode: "+677",
    countryCode: "SB",
    currencyCode: "SBD",
  },
  {
    name: "Somalia",
    dialCode: "+252",
    countryCode: "SO",
    currencyCode: "SOS",
  },
  {
    name: "South Africa",
    dialCode: "+27",
    countryCode: "ZA",
    currencyCode: "ZAR",
  },
  {
    name: "South Sudan",
    dialCode: "+211",
    countryCode: "SS",
    currencyCode: "SSP",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dialCode: "+500",
    countryCode: "GS",
    currencyCode: "GBP",
  },
  {
    name: "Spain",
    dialCode: "+34",
    countryCode: "ES",
    currencyCode: "EUR",
  },
  {
    name: "Sri Lanka",
    dialCode: "+94",
    countryCode: "LK",
    currencyCode: "LKR",
  },
  {
    name: "Sudan",
    dialCode: "+249",
    countryCode: "SD",
    currencyCode: "SDG",
  },
  {
    name: "Suriname",
    dialCode: "+597",
    countryCode: "SR",
    currencyCode: "SRD",
  },
  {
    name: "Svalbard and Jan Mayen",
    dialCode: "+47",
    countryCode: "SJ",
    currencyCode: "NOK",
  },
  {
    name: "Swaziland",
    dialCode: "+268",
    countryCode: "SZ",
    currencyCode: "SZL",
  },
  {
    name: "Sweden",
    dialCode: "+46",
    countryCode: "SE",
    currencyCode: "SEK",
  },
  {
    name: "Switzerland",
    dialCode: "+41",
    countryCode: "CH",
    currencyCode: "CHF",
  },
  {
    name: "Syrian Arab Republic",
    dialCode: "+963",
    countryCode: "SY",
    currencyCode: "SYP",
  },
  {
    name: "Taiwan",
    dialCode: "+886",
    countryCode: "TW",
    currencyCode: "TWD",
  },
  {
    name: "Tajikistan",
    dialCode: "+992",
    countryCode: "TJ",
    currencyCode: "TJS",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dialCode: "+255",
    countryCode: "TZ",
    currencyCode: "TZS",
  },
  {
    name: "Thailand",
    dialCode: "+66",
    countryCode: "TH",
    currencyCode: "THB",
  },
  {
    name: "Timor-Leste",
    dialCode: "+670",
    countryCode: "TL",
    currencyCode: "USD",
  },
  {
    name: "Togo",
    dialCode: "+228",
    countryCode: "TG",
    currencyCode: "XOF",
  },
  {
    name: "Tokelau",
    dialCode: "+690",
    countryCode: "TK",
    currencyCode: "NZD",
  },
  {
    name: "Tonga",
    dialCode: "+676",
    countryCode: "TO",
    currencyCode: "TOP",
  },
  {
    name: "Trinidad and Tobago",
    dialCode: "+1868",
    countryCode: "TT",
    currencyCode: "TTD",
  },
  {
    name: "Tunisia",
    dialCode: "+216",
    countryCode: "TN",
    currencyCode: "TND",
  },
  {
    name: "Turkey",
    dialCode: "+90",
    countryCode: "TR",
    currencyCode: "TRY",
  },
  {
    name: "Turkmenistan",
    dialCode: "+993",
    countryCode: "TM",
    currencyCode: "TMT",
  },
  {
    name: "Turks and Caicos Islands",
    dialCode: "+1649",
    countryCode: "TC",
    currencyCode: "USD",
  },
  {
    name: "Tuvalu",
    dialCode: "+688",
    countryCode: "TV",
    currencyCode: "AUD",
  },
  {
    name: "Uganda",
    dialCode: "+256",
    countryCode: "UG",
    currencyCode: "UGX",
  },
  {
    name: "Ukraine",
    dialCode: "+380",
    countryCode: "UA",
    currencyCode: "UAH",
  },
  {
    name: "United Arab Emirates",
    dialCode: "+971",
    countryCode: "AE",
    currencyCode: "AED",
  },
  {
    name: "United Kingdom",
    dialCode: "+44",
    countryCode: "GB",
    currencyCode: "GBP",
  },
  {
    name: "United States",
    dialCode: "+1",
    countryCode: "US",
    currencyCode: "USD",
  },
  {
    name: "Uruguay",
    dialCode: "+598",
    countryCode: "UY",
    currencyCode: "UYU",
  },
  {
    name: "Uzbekistan",
    dialCode: "+998",
    countryCode: "UZ",
    currencyCode: "UZS",
  },
  {
    name: "Vanuatu",
    dialCode: "+678",
    countryCode: "VU",
    currencyCode: "VUV",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dialCode: "+58",
    countryCode: "VE",
    currencyCode: "VEF",
  },
  {
    name: "Vietnam",
    dialCode: "+84",
    countryCode: "VN",
    currencyCode: "VND",
  },
  {
    name: "Virgin Islands, British",
    dialCode: "+1284",
    countryCode: "VG",
    currencyCode: "USD",
  },
  {
    name: "Virgin Islands, U.S.",
    dialCode: "+1340",
    countryCode: "VI",
    currencyCode: "USD",
  },
  {
    name: "Wallis and Futuna",
    dialCode: "+681",
    countryCode: "WF",
    currencyCode: "XPF",
  },
  {
    name: "Yemen",
    dialCode: "+967",
    countryCode: "YE",
    currencyCode: "YER",
  },
  {
    name: "Zambia",
    dialCode: "+260",
    countryCode: "ZM",
    currencyCode: "ZMW",
  },
  {
    name: "Zimbabwe",
    dialCode: "+263",
    countryCode: "ZW",
    currencyCode: "ZWL",
  },
];
