name: Merge Development into development

on:
  workflow_dispatch:

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout development branch
        run: git checkout development

      - name: Merge development into development
        run: git merge origin/development

      - name: Push changes to development
        run: git push origin development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
